# Generated by Django 4.2.5 on 2023-10-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="image_path",
            field=models.CharField(
                default="src/assets/img/offer/offer1.png", max_length=255
            ),
        ),
    ]
